---
spring:
  profiles: peer1
server:
  port: 1000
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://peer2:1001/eureka/,http://peer3:1002/eureka/
---
spring:
  profiles: peer2
server:
  port: 1001
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:1000/eureka/,http://peer3:1002/eureka/
---
spring:
  profiles: peer3
server:
  port: 1002
eureka:
  instance:
    hostname: peer3
  client:
    serviceUrl:
      defaultZone: http://peer1:1000/eureka/,http://peer2:1001/eureka/
